name: Docker Workflow

on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Clean
        run: |
          cd github-calculator
          mvn -ntp clean
      - name: Build
        run: |
          cd github-calculator
          mvn -ntp compile
      - name: Short tests
        run: |
          cd github-calculator
          mvn -ntp test -Dtest='CalculatorTest'
      - name: Long tests
        run: |
          cd github-calculator
          mvn -ntp test -Dtest='CalculatorTestThorough'
